import json
import os
import shutil

# 1. READ EXISTING QUESTIONS AND ADD 50 HVAC QUESTIONS
js_path = r'D:\LINH TINH\AI\PHAN MEM\vincons-test-app\questions.js'

with open(js_path, 'r', encoding='utf-8') as f:
    text = f.read()

questions = json.loads(text[text.find('['):text.rfind(']')+1])
print(f"Current questions count: {len(questions)}")

# Filter out any existing HVAC questions first to ensure clean state
questions = [q for q in questions if not ('điều hòa' in (q.get('category') or '').lower() or 'đhtg' in (q.get('category') or '').lower() or 'hvac' in (q.get('category') or '').lower())]

hvac_questions = [
    # 25 Bậc 2 HVAC Questions
    {"id": "q_hvac2_1", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Môi chất lạnh R32 thuộc nhóm môi chất lạnh nào sau đây?", "options": ["HFC", "HCFC", "CFC", "HC"], "correct_index": 0},
    {"id": "q_hvac2_2", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Khi thử kín hệ thống ống đồng máy điều hòa bằng khí Nitơ, áp suất thử tiêu chuẩn đối với R410A/R32 là bao nhiêu?", "options": ["1.5 MPa (~15 bar)", "2.5 MPa (~25 bar)", "4.15 MPa (~41.5 bar)", "5.5 MPa (~55 bar)"], "correct_index": 2},
    {"id": "q_hvac2_3", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Nhiệm vụ chính của máy nén (Compressor) trong hệ thống điều hòa không khí là gì?", "options": ["Hút hơi môi chất hạ áp và nén lên áp suất cao", "Làm lạnh chất lỏng", "Tăng lưu lượng gió", "Lọc bụi không khí"], "correct_index": 0},
    {"id": "q_hvac2_4", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Thiết bị nào có nhiệm vụ ngưng tụ hơi môi chất cao áp thành môi chất lỏng cao áp?", "options": ["Dàn lạnh (Evaporator)", "Dàn nóng (Condenser)", "Van tiết lưu", "Bình tích áp"], "correct_index": 1},
    {"id": "q_hvac2_5", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Độ chân không tiêu chuẩn cần đạt khi hút chân không hệ thống ĐHTG là bao nhiêu?", "options": ["Dưới 500 microns (-755 mmHg)", "Dưới 2000 microns", "Dưới 5000 microns", "Chỉ cần hút 5 phút"], "correct_index": 0},
    {"id": "q_hvac2_6", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Nguyên nhân chính khiến dàn lạnh máy điều hòa bị chảy nước dầm dề là gì?", "options": ["Tắc đường ống thoát nước đọng hoặc bẩn phin lọc", "Hệ thống nạp thừa gas", "Điện áp nguồn quá cao", "Quạt dàn nóng quay ngược"], "correct_index": 0},
    {"id": "q_hvac2_7", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Trong hệ thống ĐHTG trung tâm VRV/VRF, bộ chia gas Y-joint có vai trò gì?", "options": ["Phân phối môi chất đồng đều đến các dàn lạnh", "Giảm áp suất gas", "Lọc cặn bẩn", "Đo nhiệt độ môi chất"], "correct_index": 0},
    {"id": "q_hvac2_8", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Khi nạp bổ sung môi chất lạnh R410A, kỹ thuật viên bắt buộc phải nạp ở dạng nào?", "options": ["Nạp ở dạng lỏng", "Nạp ở dạng hơi", "Dạng nào cũng được", "Nạp hỗn hợp khí"], "correct_index": 0},
    {"id": "q_hvac2_9", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Vật liệu bảo ôn bọc ống đồng phổ biến nhất trong lắp đặt ĐHTG hiện nay là gì?", "options": ["Bông thủy tinh Glasswool", "Cao lưu hóa Superlon / Armaflex", "Mút xốp EPS", "Sợi khoáng Rockwool"], "correct_index": 1},
    {"id": "q_hvac2_10", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Độ dốc tiêu chuẩn tối thiểu của đường ống thoát nước xả dàn lạnh là bao nhiêu?", "options": ["Tối thiểu 1%", "Tối thiểu 0.1%", "Tối thiểu 5%", "Bằng phẳng nằm ngang"], "correct_index": 0},
    {"id": "q_hvac2_11", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Khi hàn nối ống đồng điều hòa, loại khí bảo vệ nào bắt buộc phải thổi qua lòng ống?", "options": ["Khí Nitơ khô (N2)", "Khí Oxy (O2)", "Khí CO2", "Khí nén tự nhiên"], "correct_index": 0},
    {"id": "q_hvac2_12", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Mục đích của việc thổi khí Nitơ qua ống đồng khi hàn là gì?", "options": ["Ngăn chặn oxy hóa tạo vảy đen (muội than) bên trong ống", "Làm mát mối hàn nhanh chóng", "Tăng độ bám dính que hàn", "Làm sạch dầu máy nén"], "correct_index": 0},
    {"id": "q_hvac2_13", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Loại que hàn tiêu chuẩn dùng để hàn nối ống đồng điều hòa là gì?", "options": ["Que hàn đồng chì hoặc hàn bạc (Phos-copper / Silver alloy)", "Que hàn điện sắt", "Que hàn nhôm", "Que hàn inox"], "correct_index": 0},
    {"id": "q_hvac2_14", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Công dụng của quạt gió dàn lạnh (Evaporator Fan) là gì?", "options": ["Thổi không khí phòng qua dàn lạnh để trao đổi nhiệt", "Thổi khí nóng ra ngoài trời", "Hút khí thải ra ngoài", "Nén hơi môi chất"], "correct_index": 0},
    {"id": "q_hvac2_15", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Áp suất hơi hút tiêu chuẩn khi máy ĐHTG dùng R22 hoạt động ổn định là khoảng bao nhiêu?", "options": ["60 - 75 PSI (~4.2 - 5.2 bar)", "120 - 140 PSI", "20 - 30 PSI", "200 PSI"], "correct_index": 0},
    {"id": "q_hvac2_16", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Áp suất hơi hút tiêu chuẩn khi máy ĐHTG dùng R32/R410A hoạt động là khoảng bao nhiêu?", "options": ["110 - 140 PSI (~7.5 - 9.6 bar)", "60 - 75 PSI", "30 - 40 PSI", "200 - 250 PSI"], "correct_index": 0},
    {"id": "q_hvac2_17", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Thiết bị van đảo chiều 4 ngả (4-way valve) được trang bị trên loại điều hòa nào?", "options": ["Điều hòa 2 chiều nóng / lạnh", "Điều hòa 1 chiều lạnh", "Quạt hơi nước", "Máy sấy khí"], "correct_index": 0},
    {"id": "q_hvac2_18", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Khi kiểm tra tụ điện quạt/nén bằng đồng hồ vạn năng, thang đo nào phù hợp nhất?", "options": ["Thang đo điện dung (Capacitance - Farad)", "Thang đo điện áp DC", "Thang đo dòng điện AC", "Thang đo tần số Hz"], "correct_index": 0},
    {"id": "q_hvac2_19", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Băng quấn simili dán bảo ôn ống đồng có tác dụng chính là gì?", "options": ["Bảo vệ lớp bảo ôn khỏi tia cực tím UV và va chạm cơ học", "Cách nhiệt trực tiếp", "Tăng áp suất ống", "Chống rò rỉ điện"], "correct_index": 0},
    {"id": "q_hvac2_20", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Khoảng cách tối thiểu từ dàn nóng điều hòa đến tường chắn phía sau là bao nhiêu?", "options": ["10 - 15 cm", "2 cm", "100 cm", "Không cần khoảng cách"], "correct_index": 0},
    {"id": "q_hvac2_21", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Ống gió mềm cách nhiệt (Flexible duct) thường được dùng ở vị trí nào trong hệ thống ĐHTG?", "options": ["Nối từ ống gió tôn chính đến miệng gió (Diffuser)", "Dùng thay thế toàn bộ ống tôn", "Lắp ngoài trời", "Chạy ngầm dưới đất"], "correct_index": 0},
    {"id": "q_hvac2_22", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Cửa gió khuếch tán (Diffuser) có vai trò gì trong hệ thống điều hòa ống gió?", "options": ["Phân phối không khí đều vào không gian điều hòa", "Lọc bụi mịn", "Sấy nóng không khí", "Đo áp suất đường ống"], "correct_index": 0},
    {"id": "q_hvac2_23", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Khi bảo dưỡng máy lạnh, chất tẩy rửa dàn nhôm chuyên dụng là loại nào?", "options": ["Hóa chất tẩy rửa dàn nhôm trung tính hoặc sinh học", "Axit clohydric đặc", "Xăng thơm", "Dầu diezel"], "correct_index": 0},
    {"id": "q_hvac2_24", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Biểu hiện hiện tượng máy điều hòa bị thiếu hụt gas môi chất lạnh là gì?", "options": ["Dàn lạnh bám tuyết ống đầu về, dòng hoạt động thấp hơn định mức", "Dàn nóng quá nóng", "Quạt dàn lạnh dừng quay", "Cầu chì nguồn bị nổ"], "correct_index": 0},
    {"id": "q_hvac2_25", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 2", "exam_set": "Thợ Điều hòa Bậc 2", "question": "Yêu cầu an toàn quan trọng nhất khi làm việc với môi chất lạnh R32 là gì?", "options": ["Không hàn cắt ống khi môi chất còn trong hệ thống vì R32 có tính cháy nhẹ (A2L)", "Không được đeo găng tay", "Hút chân không bằng miệng", "Nạp gas ở nhiệt độ cao"], "correct_index": 0},

    # 25 Bậc 3 HVAC Questions
    {"id": "q_hvac3_1", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Trong đồ thị biểu diễn chu trình nhiệt động i-d (Mollier Diagram), thông số độ ẩm tương đối được ký hiệu là gì?", "options": ["Phi (φ)", "d", "t", "i"], "correct_index": 0},
    {"id": "q_hvac3_2", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Van chặn lửa chống cháy vách (FD - Fire Damper) hoạt động tự động đóng lại khi nhiệt độ khí đạt bao nhiêu?", "options": ["70°C - 74°C (nhờ cầu chì nhiệt Melting Fusible Link)", "30°C", "150°C", "200°C"], "correct_index": 0},
    {"id": "q_hvac3_3", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Hệ thống quạt tăng áp cầu thang hiểm (Stairwell Pressurization Fan) hoạt động để duy trì độ chênh áp là bao nhiêu?", "options": ["20 Pa đến 50 Pa so với khu vực lân cận", "100 Pa đến 200 Pa", "1 Pa đến 5 Pa", "500 Pa"], "correct_index": 0},
    {"id": "q_hvac3_4", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Trong hệ thống Chiller giải nhiệt nước (Water-cooled Chiller), thiết bị nào giải nhiệt cho bình ngưng tụ?", "options": ["Tháp giải nhiệt (Cooling Tower)", "Dàn lạnh FCU", "Bơm nước lạnh Chilled Water Pump", "Bình bù áp"], "correct_index": 0},
    {"id": "q_hvac3_5", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Nhiệt độ nước lạnh cấp (Chilled Water Supply) tiêu chuẩn ra khỏi máy Chiller thường là bao nhiêu?", "options": ["7°C (nước về khoảng 12°C)", "0°C", "15°C", "25°C"], "correct_index": 0},
    {"id": "q_hvac3_6", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Chức năng của van cân bằng thủy lực (Balancing Valve) trong hệ thống nước lạnh Chiller là gì?", "options": ["Điều chỉnh phân phối lưu lượng nước lạnh cân bằng giữa các nhánh", "Lọc cặn rác", "Tăng áp suất bơm", "Tự động xả khí"], "correct_index": 0},
    {"id": "q_hvac3_7", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Trong hệ thống VRV/VRF, công nghệ Inverter thay đổi công suất máy nén bằng cách nào?", "options": ["Thay đổi tần số dòng điện cấp cho động cơ máy nén", "Bật tắt máy nén liên tục", "Xả bớt gas ra ngoài", "Tăng điện áp nguồn"], "correct_index": 0},
    {"id": "q_hvac3_8", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bợc 3", "question": "Thiết bị AHU (Air Handling Unit) khác FCU (Fan Coil Unit) ở điểm cơ bản nào?", "options": ["AHU có công suất gió lớn, xử lý không khí tươi và kết hợp nhiều lớp lọc chuyên dụng", "AHU không dùng nước lạnh", "AHU chỉ lắp ở phòng ngủ", "AHU dùng điện 1 pha"], "correct_index": 0},
    {"id": "q_hvac3_9", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Phin lọc không khí tinh HEPA (High Efficiency Particulate Air) trong phòng sạch có khả năng lọc bụi bao nhiêu?", "options": ["Lọc 99.97% hạt bụi kích thước từ 0.3 microns", "Chỉ lọc bụi thô 100 microns", "Lọc 50% bụi", "Chỉ lọc được vi khuẩn"], "correct_index": 0},
    {"id": "q_hvac3_10", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Hiện tượng va đập thủy lực (Liquid Hammer / Liquid Slug) trong máy nén điều hòa xảy ra khi nào?", "options": ["Môi chất lỏng chưa bay hơi hết bị hút vào xi lanh máy nén", "Áp suất hơi hút quá thấp", "Điện áp bị giảm", "Nhiệt độ ngoài trời thấp"], "correct_index": 0},
    {"id": "q_hvac3_11", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Chức năng của bình tách lỏng (Accumulator) đặt trước đường hút máy nén là gì?", "options": ["Ngăn chặn môi chất lạnh dạng lỏng đi lọt vào máy nén", "Làm ngưng tụ gas", "Tăng áp suất gas", "Lọc dầu mỡ"], "correct_index": 0},
    {"id": "q_hvac3_12", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Bình tách dầu (Oil Separator) trong hệ thống điều hòa trung tâm được lắp ở vị trí nào?", "options": ["Đường đẩy ra của máy nén (Discharge Line)", "Đường hút máy nén", "Sau dàn lạnh", "Sau van tiết lưu"], "correct_index": 0},
    {"id": "q_hvac3_13", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Độ quá nhiệt (Superheat) của môi chất lạnh tại đầu ra dàn lạnh được tính bằng công thức nào?", "options": ["Superheat = Nhiệt độ ống hút - Nhiệt độ bay hơi bão hòa", "Superheat = Nhiệt độ ngưng tụ - Nhiệt độ ống hút", "Superheat = Nhiệt độ phòng - Nhiệt độ cài đặt", "Superheat = Áp suất hút - Áp suất đẩy"], "correct_index": 0},
    {"id": "q_hvac3_14", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Độ quá lạnh (Subcooling) tại đầu ra dàn nóng được tính bằng công thức nào?", "options": ["Subcooling = Nhiệt độ ngưng tụ bão hòa - Nhiệt độ ống lỏng", "Subcooling = Nhiệt độ phòng - Nhiệt độ lỏng", "Subcooling = Áp suất cao - Áp suất thấp", "Subcooling = Nhiệt độ bay hơi - Nhiệt độ lỏng"], "correct_index": 0},
    {"id": "q_hvac3_15", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Van tiết lưu điện tử (EEV - Electronic Expansion Valve) điều khiển lưu lượng gas dựa vào thông số nào?", "options": ["Độ quá nhiệt (Superheat) tính từ cảm biến nhiệt độ và áp suất", "Dòng điện quạt", "Nhiệt độ môi trường ngoài trời", "Độ ẩm không khí"], "correct_index": 0},
    {"id": "q_hvac3_16", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Tiêu chuẩn kiểm tra thử kín ống gió (Duct Leakage Test) thường căn cứ theo tiêu chuẩn quốc tế nào?", "options": ["DW/144 hoặc SMACNA", "NFPA 70", "ASHRAE 90.1", "ISO 9001"], "correct_index": 0},
    {"id": "q_hvac3_17", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Bơm nước xả ngưng tích hợp trong dàn lạnh Âm trần Cassette được điều khiển bởi thiết bị nào?", "options": ["Phao cảm biến mực nước đọng (Float Switch)", "Rơ le nhiệt", "Công tắc dòng chảy", "Cảm biến phòng"], "correct_index": 0},
    {"id": "q_hvac3_18", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Trong hệ thống ĐHTG, van chặn khói (SD - Smoke Damper) nhận tín hiệu điều khiển đóng/mở từ đâu?", "options": ["Hệ thống báo cháy trung tâm (Fire Alarm Panel)", "Đồng hồ áp suất", "Cảm biến nhiệt độ phòng", "Công tắc quạt"], "correct_index": 0},
    {"id": "q_hvac3_19", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Hệ thống quạt hút khói hành lang (Smoke Extraction Fan) yêu cầu chịu nhiệt tiêu chuẩn tối thiểu là bao nhiêu?", "options": ["280°C trong 2 giờ hoặc 300°C trong 2 giờ", "100°C trong 30 phút", "500°C trong 10 giờ", "Chỉ cần quạt thông thường"], "correct_index": 0},
    {"id": "q_hvac3_20", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Khi hút chân không hệ thống Chiller cỡ lớn, tại sao không được nạp môi chất lỏng ngay từ đầu khi áp suất đang chân không?", "options": ["Vì gây sôi đột ngột làm đóng băng vỡ ống đồng trong bình nén/bình bay hơi", "Vì làm hỏng van nạp", "Vì cháy cầu chì", "Vì làm hỏng quạt gió"], "correct_index": 0},
    {"id": "q_hvac3_21", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Công dụng của công tắc dòng chảy (Flow Switch) lắp trên đường ống nước Chiller là gì?", "options": ["Bảo vệ máy nén/Chiller dừng chạy khi mất dòng chảy nước", "Đo áp suất nước", "Lọc cặn bẩn", "Điều chỉnh nhiệt độ nước"], "correct_index": 0},
    {"id": "q_hvac3_22", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Bình giãn nở áp lực (Expansion Tank) trong hệ thống nước lạnh Chiller có vai trò gì?", "options": ["Hấp thụ sự giãn nở thể tích nước khi nhiệt độ thay đổi và duy trì áp suất hệ thống", "Dự trữ nước sinh hoạt", "Làm sạch nước", "Cung cấp nước nóng"], "correct_index": 0},
    {"id": "q_hvac3_23", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Trong vận hành hệ thống VRV, mã lỗi E3 trên dàn nóng Daikin thường báo hiệu sự cố gì?", "options": ["Tác động của rơ le cao áp (High Pressure Switch)", "Lỗi dây tín hiệu", "Lỗi quạt dàn lạnh", "Hết gas hoàn toàn"], "correct_index": 0},
    {"id": "q_hvac3_24", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Biện pháp xử lý chuẩn kỹ thuật khi đường ống đồng điều hòa VRV bị rò rỉ môi chất R410A là gì?", "options": ["Thu hồi gas còn lại, khắc phục điểm rò, thử kín Nitơ 4.15MPa, hút chân không <500microns và nạp lại gas mới theo trọng lượng", "Chỉ cần hàn dặm và nạp thêm gas hơi", "Nạp đè R32 vào", "Xả hết gas ra không khí và chạy tiếp"], "correct_index": 0},
    {"id": "q_hvac3_25", "type": "multiple_choice", "category": "Lý thuyết - Thợ Điều hòa Bậc 3", "exam_set": "Thợ Điều hòa Bậc 3", "question": "Chỉ số COP (Coefficient of Performance) của máy điều hòa được tính bằng tỷ số nào?", "options": ["Năng suất lạnh sản sinh (kW) / Công suất điện tiêu thụ (kW)", "Dòng điện / Điện áp", "Khối lượng gas / Thời gian", "Lưu lượng gió / Áp suất gió"], "correct_index": 0}
]

questions.extend(hvac_questions)
print(f"Total questions after adding 50 HVAC questions: {len(questions)}")

new_js = f"// File questions.js - Tích hợp đầy đủ 50 câu hỏi Điều hòa thông gió (HVAC)\nconst QUESTIONS = {json.dumps(questions, ensure_ascii=False, indent=2)};\n"

js_paths = [
    r'D:\LINH TINH\AI\PHAN MEM\vincons-test-app\questions.js',
    r'D:\LINH TINH\AI\PHAN MEM\vincons-test-app\apk_unpacked\assets\www\questions.js',
    r'D:\LINH TINH\AI\PHAN MEM\vincons-test-app\android_build\android\app\src\main\assets\public\questions.js',
    r'D:\LINH TINH\AI\PHAN MEM\vincons-test-app\android_build\www\questions.js'
]

for p in js_paths:
    if os.path.exists(os.path.dirname(p)):
        with open(p, 'w', encoding='utf-8') as f:
            f.write(new_js)
        print(f"✅ Saved questions.js to {p}")
